Updated readme
mjirous/cinject pull request #1
Opened 2017-07-05 15:20 UTC by Resurr3ction

Fixed some typos and a bit of grammar. Added info on the project structure is it was not clear that src/ contains a sample project for example.

2017-07-07 12:24 UTC, mjirous requested changes
Thanks for the changes, but please fix the one comment, where you accidentaly renamed #include filename

2017-07-07 12:24 UTC, mjirous commented on README.md
> +#include <Cinject/Cinject.h>
This should stay as before

2017-07-08 13:36 UTC, Resurr3ction commented on README.md
> +#include <Cinject/Cinject.h>
Fixed that just now. Good eye!

2017-07-10 07:18 UTC, mjirous approved these changes

2017-07-10 07:20 UTC, merged